import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
  id 'com.android.library'
  id 'com.vanniktech.maven.publish'
}

android {
  namespace 'com.nightlynexus.diskcrashreporter'

  compileSdk 36

  defaultConfig {
    minSdkVersion 21
  }

  lintOptions {
    abortOnError true
    warningsAsErrors true
    textReport true
    textOutput 'stdout'
    htmlReport true
    htmlOutput rootProject.file("lint-reports/${name}.html")
  }

  compileOptions {
    sourceCompatibility JavaVersion.VERSION_11
    targetCompatibility JavaVersion.VERSION_11
  }

  kotlin {
    compilerOptions {
      jvmTarget = JvmTarget.JVM_11
    }
  }
}

repositories {
  google()
  mavenCentral()
}

dependencies {
  implementation 'androidx.core:core:1.18.0'
  implementation 'androidx.annotation:annotation:1.9.1'
  implementation 'com.squareup.okio:okio:3.17.0'
  implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.3.10'
}
