buildscript {
  dependencies {
    classpath 'com.android.tools.build:gradle:9.1.0'
    classpath 'com.vanniktech:gradle-maven-publish-plugin:0.36.0'
    classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:2.3.10'
  }

  repositories {
    google()
    gradlePluginPortal()
    mavenCentral()
  }
}

allprojects {
  tasks.withType(JavaCompile) {
    options.compilerArgs += ['-Xlint:all', '-Werror']
  }
}
